
  /tuts:
    get:
     summary: Get all tutss
     tags: [tuts]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/tuts'
 
    post:
      summary: Create tuts
      tags: [tuts]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tuts'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tuts'
 
  /tuts/{id}:
    get:
      summary: Get tuts by id
      tags: [tuts]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tuts'
 
    put:
      summary: Edit tuts
      tags: [tuts]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tuts'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/tuts'
 
    delete:
      summary: Delete tuts
      tags: [tuts]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tuts'

  /user:
    get:
     summary: Get all users
     tags: [user]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/user'
 
    post:
      summary: Create user
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
  /user/{id}:
    get:
      summary: Get user by id
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
    put:
      summary: Edit user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/user'
 
    delete:
      summary: Delete user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  components:
    schemas:
  
      tuts:
        type: object
        properties:
      
          id:
            type: string
          title:
            type: string
          exp:
            type: string
      user:
        type: object
        properties:
      
          id:
            type: number
          name:
            type: string
          email:
            type: string
          gender:
            type: string
          password:
            type: string